name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      semanticVersion:
        description: 'Semantic Version [major|minor|patch]'
        required: true
        default: 'patch'

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          ref: 'master'

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install node modules
        run: yarn install

      - name: Build
        run: yarn build

      - name: run localstack
        run: docker-compose build

      - name: run localstack
        run: docker-compose up -d

      - name: wait for localstack
        run: ./scripts/wait-for-url.js http://localhost:4575 && sleep 5

      - name: Test
        run: yarn test

      - name: Configure CI Git User
        run: |
          git config --global user.name '@aspecto-system'
          git config --global user.email 'aspecto-system@users.noreply.github.com'

      - name: Update yarn commit message
        run: yarn config set version-git-message "chore(release) - publish v%s"

      - name: Bump Version
        run: yarn version --${{ github.event.inputs.semanticVersion }} --no-commit-hooks

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Version Update
        run: git push
